# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170225_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text="<pre class='prettyprint'></pre>"),
        ),
    ]
